spring.jackson.parser.allow-non-numeric-numbers: true

spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mariadb://localhost:3306/dev
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: a12345678
  messages:
    basename: messages/messages
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    